// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using User_Management_System.Data.Context;

#nullable disable

namespace User_Management_System.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("User_Management_System.Entities.User.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 11, 7, 23, 15, 18, 742, DateTimeKind.Local).AddTicks(2814),
                            LastUpdateDate = new DateTime(2024, 11, 7, 23, 15, 18, 742, DateTimeKind.Local).AddTicks(2814),
                            Name = "مدیریت"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 11, 7, 23, 15, 18, 742, DateTimeKind.Local).AddTicks(2815),
                            LastUpdateDate = new DateTime(2024, 11, 7, 23, 15, 18, 742, DateTimeKind.Local).AddTicks(2816),
                            Name = "کاربر"
                        });
                });

            modelBuilder.Entity("User_Management_System.Entities.User.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 11, 7, 23, 15, 18, 742, DateTimeKind.Local).AddTicks(2581),
                            Email = "MobinEffati@gmail.com",
                            LastUpdateDate = new DateTime(2024, 11, 7, 23, 15, 18, 742, DateTimeKind.Local).AddTicks(2588),
                            Password = "12481632",
                            UserName = "MobinEfati"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 11, 7, 23, 15, 18, 742, DateTimeKind.Local).AddTicks(2590),
                            Email = "ElhamAzizzade@gmail.com",
                            LastUpdateDate = new DateTime(2024, 11, 7, 23, 15, 18, 742, DateTimeKind.Local).AddTicks(2590),
                            Password = "12481632",
                            UserName = "ElhamAzizzade"
                        });
                });

            modelBuilder.Entity("User_Management_System.Entities.User.UserRole", b =>
                {
                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("RoleID", "UserID");

                    b.HasIndex("UserID");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            UserID = 1
                        },
                        new
                        {
                            RoleID = 2,
                            UserID = 2
                        });
                });

            modelBuilder.Entity("User_Management_System.Entities.User.UserRole", b =>
                {
                    b.HasOne("User_Management_System.Entities.User.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User_Management_System.Entities.User.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("User_Management_System.Entities.User.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("User_Management_System.Entities.User.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
